### ISSUE TITLE
strpos for searching for a metric inside searchMetrics

### ISSUE THREAD

**Issue by dknx01** [damianopetrungaro/CachetSDK#2]
Hi,
I have a question. You use strpo inside the searchMetrics method for finding a metric. I think a complete string comparison would be better. In my use case I have multiple metrics with some equals parts e.g. Dashboard and Dashbord_Live. At the moment I always get the first item back if I search for "Dashboard", which must not be the right one.
In my case it was for testing cachet and your SDK and the metric name still changes from time to time.

**Comment by damianopetrungaro** [comment]
Hi @dknx01!

As you can see there's a limit parameter set to 1 by default.
If you set it different to 1 (0 for example), you will get all the metrics with the found string.

Re-Open if you want :smile:
